-- SPDX-FileCopyrightText: 2026 my04337
-- SPDX-License-Identifier: MIT

import S2IL
import Lean

/-!
# 証明依存グラフ生成ツール (DepGraph)

S2IL プロジェクト内の定理・定義間の依存関係を
Lean の `Environment` API から抽出し、Mermaid または JSON 形式で出力する。

## 使用方法

```
lake exe depgraph [OPTIONS]
```

### オプション

| フラグ | 説明 |
|---|---|
| `--private` | private 宣言を含める |
| `--json` | JSON 形式で出力（デフォルト: Mermaid） |
| `--ns <prefix>` | 対象モジュールプレフィックス（デフォルト: `S2IL`） |
| `--theorems-only` | 定理のみ表示（定義を除外） |
| `--output <path>` | 出力ファイルパス（デフォルト: stdout） |
-/

open Lean

namespace DepGraph

-- ============================================================
-- コマンドライン引数
-- ============================================================

/-- コマンドライン設定 -/
structure Config where
    /-- private 宣言を含めるか -/
    includePrivate : Bool := false
    /-- JSON 形式で出力するか（false なら Mermaid） -/
    jsonOutput : Bool := false
    /-- 対象モジュールプレフィックス -/
    nsPrefix : String := "S2IL"
    /-- 定理のみ表示するか -/
    theoremsOnly : Bool := false
    /-- 出力ファイルパス（None なら stdout） -/
    outputPath : Option String := none
    /-- 起点となる宣言名（指定時はこの宣言を含む部分グラフのみ出力） -/
    rootDecl : Option String := none
    /-- 起点を逆向きにたどるか（true: この宣言を利用している宣言を辿る） -/
    rootReverse : Bool := false

/-- コマンドライン引数を再帰的に解析する -/
def parseArgs : List String → Config → Config
    | "--private" :: rest, cfg => parseArgs rest { cfg with includePrivate := true }
    | "--json" :: rest, cfg => parseArgs rest { cfg with jsonOutput := true }
    | "--ns" :: ns :: rest, cfg => parseArgs rest { cfg with nsPrefix := ns }
    | "--theorems-only" :: rest, cfg => parseArgs rest { cfg with theoremsOnly := true }
    | "--output" :: p :: rest, cfg => parseArgs rest { cfg with outputPath := some p }
    | "--root" :: decl :: rest, cfg => parseArgs rest { cfg with rootDecl := some decl }
    | "--root-reverse" :: rest, cfg => parseArgs rest { cfg with rootReverse := true }
    | _ :: rest, cfg => parseArgs rest cfg
    | [], cfg => cfg

-- ============================================================
-- 宣言の分類
-- ============================================================

/-- 宣言の種別 -/
inductive DeclKind where
    | «theorem»
    | «def»
    | «axiom»
    | «opaque»
    | «inductive»
    deriving BEq

instance : ToString DeclKind where
    toString
        | .theorem => "theorem"
        | .def => "def"
        | .axiom => "axiom"
        | .opaque => "opaque"
        | .inductive => "inductive"

/-- ConstantInfo を宣言種別に分類する。
    コンストラクタ・再帰子は自動生成のためスキップ（none を返す）。 -/
def classifyDecl (ci : ConstantInfo) : Option DeclKind :=
    match ci with
    | .thmInfo _ => some .theorem
    | .defnInfo _ => some .def
    | .axiomInfo _ => some .axiom
    | .opaqueInfo _ => some .opaque
    | .inductInfo _ => some .inductive
    | .ctorInfo _ | .recInfo _ => none
    | _ => none

-- ============================================================
-- ノード・エッジ
-- ============================================================

/-- グラフのノード情報 -/
structure Node where
    /-- 宣言の完全修飾名 -/
    name : Name
    /-- 宣言の種別 -/
    kind : DeclKind
    /-- 定義元のモジュール名 -/
    moduleName : Name
    /-- sorry を使用しているか -/
    hasSorry : Bool
    /-- private 宣言か -/
    isPrivate : Bool

-- ============================================================
-- 参照定数の収集
-- ============================================================

/-- コンパイラが自動生成した定理（sizeOf_spec, DecidableEq proof 等）を判定する。
    これらはユーザーが記述した証明ではないため、デフォルトでグラフから除外する。 -/
def isAutoGenerated (n : Name) : Bool :=
    let s := toString n
    s.containsSubstr "sizeOf_spec" ||
    s.containsSubstr "._proof_" ||
    s.containsSubstr ".ofNat_ctorIdx" ||
    s.containsSubstr ".match_" ||
    s.containsSubstr "._uniq" ||
    s.containsSubstr ".noConfusion" ||
    s.containsSubstr ".brecOn" ||
    s.containsSubstr ".injEq" ||
    s.containsSubstr ".inj" && s.endsWith ".inj" ||
    s.containsSubstr ".eq_1" ||
    s.containsSubstr ".eq_2" ||
    s.containsSubstr ".eq_def" ||
    s.containsSubstr "._sparseCasesOn" ||
    s.containsSubstr ".else_eq" ||
    s.containsSubstr ".congr_simp"

/-- ConstantInfo の型シグネチャと値（証明本体）から
    参照される全定数名を収集する -/
def collectRefs (ci : ConstantInfo) : NameSet :=
    -- まず型シグネチャから収集
    let s := ci.type.foldConsts {} fun n acc => acc.insert n
    -- 次に値/証明本体から収集（存在する場合）
    match ci with
    | .thmInfo val => val.value.foldConsts s fun n acc => acc.insert n
    | .defnInfo val => val.value.foldConsts s fun n acc => acc.insert n
    | .opaqueInfo val => val.value.foldConsts s fun n acc => acc.insert n
    | _ => s

-- ============================================================
-- Mermaid ID のサニタイズ
-- ============================================================

/-- Name を Mermaid 安全な ID 文字列に変換する -/
def sanitizeId (n : Name) : String :=
    let s := toString n
    s.toList.map (fun c =>
        if c.isAlphanum || c == '_' then c else '_'
    ) |> String.ofList

-- ============================================================
-- グラフ構築
-- ============================================================

/-- 環境からノードとエッジを収集する。
    モジュール単位でフィルタリングし、対象ノード間のエッジのみを返す。 -/
def buildGraph (env : Environment) (cfg : Config) :
        Array Node × Array (Name × Name) := Id.run do
    let moduleNames := env.header.moduleNames
    let moduleData := env.header.moduleData

    -- Phase 1: 対象ノード名の収集（エッジフィルタ用）
    let mut targetNames : NameSet := {}
    for i in [:moduleNames.size] do
        let modName := moduleNames[i]!
        unless modName.toString.startsWith cfg.nsPrefix do continue
        if i >= moduleData.size then continue
        let mdata := moduleData[i]!
        for j in [:mdata.constNames.size] do
            let name := mdata.constNames[j]!
            -- private フィルタ
            if !cfg.includePrivate && isPrivateName name then continue
            -- 自動生成された宣言をスキップ
            if !cfg.includePrivate && isAutoGenerated name then continue
            if let some info := env.find? name then
                if let some kind := classifyDecl info then
                    -- theorems-only フィルタ
                    if cfg.theoremsOnly && kind != .theorem then continue
                    targetNames := targetNames.insert name

    -- Phase 2: ノード情報・エッジの構築
    let mut nodes : Array Node := #[]
    let mut edges : Array (Name × Name) := #[]
    for i in [:moduleNames.size] do
        let modName := moduleNames[i]!
        unless modName.toString.startsWith cfg.nsPrefix do continue
        if i >= moduleData.size then continue
        let mdata := moduleData[i]!
        for j in [:mdata.constNames.size] do
            let name := mdata.constNames[j]!
            unless targetNames.contains name do continue
            if let some info := env.find? name then
                let kind := (classifyDecl info).getD .def
                let refs := collectRefs info
                let hasSorry := refs.contains ``sorryAx
                let isPriv := isPrivateName name
                nodes := nodes.push {
                    name
                    kind
                    moduleName := modName
                    hasSorry
                    isPrivate := isPriv
                }
                -- 対象ノード間のエッジのみ追加（自己参照は除外）
                for ref in refs.toList do
                    if ref != name && targetNames.contains ref then
                        edges := edges.push (name, ref)
    return (nodes, edges)

-- ============================================================
-- 起点フィルタ
-- ============================================================

/-- 指定した起点宣言から到達可能なノード・エッジに絞り込む。
    reverse = false: 起点が依存するすべての宣言（依存先を辿る）
    reverse = true:  起点を利用するすべての宣言（依存元を辿る） -/
def filterByRoot (rootDecl : Name) (nodes : Array Node) (edges : Array (Name × Name))
        (reverse : Bool) : Array Node × Array (Name × Name) := Id.run do
    -- エッジを辿る方向の隣接リストを構築
    let mut adj : NameMap (Array Name) := {}
    for (src, tgt) in edges do
        if reverse then
            -- リバース: tgt から src を辿る（tgt を使っているのは誰か）
            let cur := (adj.find? tgt).getD #[]
            adj := adj.insert tgt (cur.push src)
        else
            -- フォワード: src から tgt を辿る（src が依存しているのは何か）
            let cur := (adj.find? src).getD #[]
            adj := adj.insert src (cur.push tgt)
    -- BFS で到達可能ノードを収集
    let mut visited : NameSet := {}
    let mut queue : Array Name := #[rootDecl]
    visited := visited.insert rootDecl
    while queue.size > 0 do
        let cur := queue[0]!
        queue := queue.extract 1 queue.size
        for next in (adj.find? cur).getD #[] do
            unless visited.contains next do
                visited := visited.insert next
                queue := queue.push next
    -- 到達可能なノード・エッジのみに絞り込む
    let filtNodes := nodes.filter fun n => visited.contains n.name
    let filtEdges := edges.filter fun (s, t) => visited.contains s && visited.contains t
    return (filtNodes, filtEdges)

-- ============================================================
-- Mermaid 出力
-- ============================================================

/-- Mermaid 形式のグラフ文字列を生成する -/
def formatMermaid (nodes : Array Node) (edges : Array (Name × Name)) : String :=
    Id.run do
    let mut out := "graph TD\n"
    -- モジュールごとにサブグラフとしてグループ化
    let moduleList := (nodes.map (·.moduleName)).toList.eraseDups
    for modName in moduleList do
        let modNodes := nodes.filter (·.moduleName == modName)
        out := out ++ s!"    subgraph {modName}\n"
        for node in modNodes do
            let id := sanitizeId node.name
            let label := toString node.name
            let kindStr := toString node.kind
            if node.hasSorry then
                out := out ++ s!"        {id}[\"{label}  sorry {kindStr}\"]\n"
                out := out ++ s!"        style {id} fill:#ffcccc,stroke:#ff0000\n"
            else
                out := out ++ s!"        {id}[\"{label}  {kindStr}\"]\n"
        out := out ++ "    end\n"
    -- エッジ出力
    for (src, tgt) in edges do
        out := out ++ s!"    {sanitizeId src} --> {sanitizeId tgt}\n"
    return out

-- ============================================================
-- JSON 出力
-- ============================================================

/-- JSON 形式のグラフ文字列を生成する -/
def formatJson (nodes : Array Node) (edges : Array (Name × Name)) : String :=
    let nodeArr := nodes.map fun n =>
        Json.mkObj [
            ("name", .str (toString n.name)),
            ("kind", .str (toString n.kind)),
            ("module", .str (toString n.moduleName)),
            ("sorry", .bool n.hasSorry),
            ("private", .bool n.isPrivate)
        ]
    let edgeArr := edges.map fun (s, t) =>
        Json.mkObj [
            ("from", .str (toString s)),
            ("to", .str (toString t))
        ]
    let root := Json.mkObj [
        ("nodes", Json.arr nodeArr),
        ("edges", Json.arr edgeArr)
    ]
    root.pretty

end DepGraph

-- ============================================================
-- エントリポイント
-- ============================================================

unsafe def main (args : List String) : IO Unit := do
    let cfg := DepGraph.parseArgs args {}

    -- 検索パスの初期化
    Lean.initSearchPath (← Lean.findSysroot)

    -- S2IL 環境をロード
    let env ← Lean.importModules #[{ module := `S2IL }] {}

    -- グラフ構築
    let (nodes, edges) := DepGraph.buildGraph env cfg

    -- 起点フィルタの適用
    let (outNodes, outEdges) ← match cfg.rootDecl with
        | none => pure (nodes, edges)
        | some rootStr =>
            let rootName := rootStr.toName
            if nodes.any (·.name == rootName) then
                pure (DepGraph.filterByRoot rootName nodes edges cfg.rootReverse)
            else do
                IO.eprintln s!"Warning: root declaration '{rootStr}' not found in graph."
                pure (nodes, edges)

    -- 出力フォーマットの選択
    let output := if cfg.jsonOutput
        then DepGraph.formatJson outNodes outEdges
        else DepGraph.formatMermaid outNodes outEdges

    -- ファイルまたは stdout に出力
    match cfg.outputPath with
    | some path => IO.FS.writeFile ⟨path⟩ output
    | none => IO.print output

    -- 統計情報を stderr に出力
    let sorryCount := (outNodes.filter (·.hasSorry)).size
    let thmCount := (outNodes.filter fun n => n.kind == .theorem).size
    IO.eprintln "=== DEPGRAPH STATISTICS ==="
    IO.eprintln s!"  nodes: {outNodes.size} (theorems: {thmCount}, other: {outNodes.size - thmCount})"
    IO.eprintln s!"  edges: {outEdges.size}"
    if sorryCount > 0 then
        IO.eprintln s!"  sorry: {sorryCount}"
    IO.eprintln "=== END STATISTICS ==="
