-- SPDX-FileCopyrightText: 2026 my04337
-- SPDX-License-Identifier: MIT

import S2IL
import Lean

/-!
# 共通定義（Toolkit 内部）

depgraph / symbol-map / proof-stats で共有される型定義とユーティリティ。
-/

open Lean

namespace DevTool.Toolkit.Common

-- ============================================================
-- 宣言の分類
-- ============================================================

/-- 宣言の種別 -/
inductive DeclKind where
    | «theorem»
    | «def»
    | «axiom»
    | «opaque»
    | «inductive»
    deriving BEq

instance : ToString DeclKind where
    toString
        | .theorem => "theorem"
        | .def => "def"
        | .axiom => "axiom"
        | .opaque => "opaque"
        | .inductive => "inductive"

/-- ConstantInfo を宣言種別に分類する。
    コンストラクタ・再帰子は自動生成のためスキップ（none を返す）。 -/
def classifyDecl (ci : ConstantInfo) : Option DeclKind :=
    match ci with
    | .thmInfo _ => some .theorem
    | .defnInfo _ => some .def
    | .axiomInfo _ => some .axiom
    | .opaqueInfo _ => some .opaque
    | .inductInfo _ => some .inductive
    | .ctorInfo _ | .recInfo _ => none
    | _ => none

-- ============================================================
-- ノード情報
-- ============================================================

/-- グラフのノード情報 -/
structure Node where
    /-- 宣言の完全修飾名 -/
    name : Name
    /-- 宣言の種別 -/
    kind : DeclKind
    /-- 定義元のモジュール名 -/
    moduleName : Name
    /-- sorry を使用しているか -/
    hasSorry : Bool
    /-- private 宣言か -/
    isPrivate : Bool

-- ============================================================
-- ユーティリティ
-- ============================================================

/-- コンパイラが自動生成した定理（sizeOf_spec, DecidableEq proof 等）を判定する。
    これらはユーザーが記述した証明ではないため、デフォルトでグラフから除外する。 -/
def isAutoGenerated (n : Name) : Bool :=
    let s := toString n
    s.containsSubstr "sizeOf_spec" ||
    s.containsSubstr "._proof_" ||
    s.containsSubstr ".ofNat_ctorIdx" ||
    s.containsSubstr ".match_" ||
    s.containsSubstr "._uniq" ||
    s.containsSubstr ".noConfusion" ||
    s.containsSubstr ".brecOn" ||
    s.containsSubstr ".injEq" ||
    s.containsSubstr ".inj" && s.endsWith ".inj" ||
    s.containsSubstr ".eq_1" ||
    s.containsSubstr ".eq_2" ||
    s.containsSubstr ".eq_def" ||
    s.containsSubstr "._sparseCasesOn" ||
    s.containsSubstr ".else_eq" ||
    s.containsSubstr ".congr_simp"

/-- ConstantInfo の型シグネチャと値（証明本体）から
    参照される全定数名を収集する -/
def collectRefs (ci : ConstantInfo) : NameSet :=
    -- まず型シグネチャから収集
    let s := ci.type.foldConsts {} fun n acc => acc.insert n
    -- 次に値/証明本体から収集（存在する場合）
    match ci with
    | .thmInfo val => val.value.foldConsts s fun n acc => acc.insert n
    | .defnInfo val => val.value.foldConsts s fun n acc => acc.insert n
    | .opaqueInfo val => val.value.foldConsts s fun n acc => acc.insert n
    | _ => s

/-- Lean モジュール名をファイルパスに変換する。
    例: S2IL.Operations.Gravity.Facade → S2IL/Operations/Gravity/Facade.lean -/
def filePathFromModule (modName : Name) : String :=
    let parts := modName.toString.splitOn "."
    String.intercalate "/" parts ++ ".lean"

/-- 環境から対象ノード一覧を構築する。
    depgraph / symbol-map / proof-stats の全機能で共有する。 -/
def buildNodes (env : Environment) (nsPrefix : String)
        (includePrivate : Bool) (sorriesOnly : Bool) (theoremsOnly : Bool) :
        Array Node := Id.run do
    let moduleNames := env.header.moduleNames
    let moduleData := env.header.moduleData
    let mut nodes : Array Node := #[]
    for i in [:moduleNames.size] do
        let modName := moduleNames[i]!
        unless modName.toString.startsWith nsPrefix do continue
        if i >= moduleData.size then continue
        let mdata := moduleData[i]!
        for j in [:mdata.constNames.size] do
            let name := mdata.constNames[j]!
            if !(includePrivate || sorriesOnly) && isPrivateName name then continue
            if !includePrivate && isAutoGenerated name then continue
            if let some info := env.find? name then
                if let some kind := classifyDecl info then
                    if theoremsOnly && kind != .theorem then continue
                    let refs := collectRefs info
                    let hasSorry := refs.contains ``sorryAx
                    let isPriv := isPrivateName name
                    nodes := nodes.push {
                        name, kind, moduleName := modName, hasSorry, isPrivate := isPriv
                    }
    return nodes

/-- 環境から対象ノード間のエッジを構築する -/
def buildEdges (env : Environment) (nodes : Array Node) : Array (Name × Name) := Id.run do
    let targetNames : NameSet := nodes.foldl (fun s n => s.insert n.name) {}
    let mut edges : Array (Name × Name) := #[]
    for node in nodes do
        if let some info := env.find? node.name then
            let refs := collectRefs info
            for ref in refs.toList do
                if ref != node.name && targetNames.contains ref then
                    edges := edges.push (node.name, ref)
    return edges

/-- S2IL 環境をロードする -/
unsafe def loadEnv : IO Environment := do
    Lean.initSearchPath (← Lean.findSysroot)
    Lean.importModules #[{ module := `S2IL }] {}

end DevTool.Toolkit.Common
